<a href="https://colab.research.google.com/github/marif1991/pytorch-owais/blob/main/Tensor_maths.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
torch_a = torch.tensor([1,2,3,4,5])
torch_b =torch.tensor([6,7,8,9,10])


In [3]:
#addition
torch_a + torch_b

tensor([ 7,  9, 11, 13, 15])

In [5]:
#adding function
torch.add(torch_a, torch_b)

tensor([ 7,  9, 11, 13, 15])

In [6]:
torch_a*torch_b

tensor([ 6, 14, 24, 36, 50])

In [7]:
torch_b-torch_a

tensor([5, 5, 5, 5, 5])

In [8]:
torch_b/torch_a

tensor([6.0000, 3.5000, 2.6667, 2.2500, 2.0000])

In [9]:
#multiplying function
torch.multiply(torch_a,torch_b)

tensor([ 6, 14, 24, 36, 50])

In [12]:
#substracting function
torch.subtract(torch_b,torch_a)

tensor([5, 5, 5, 5, 5])

In [14]:
#division function
torch.divide(torch_b,torch_a)

tensor([6.0000, 3.5000, 2.6667, 2.2500, 2.0000])

In [16]:
#reminder modulus
torch_b % torch_a

tensor([0, 1, 2, 1, 0])

In [21]:
#reminder function
torch.remainder(torch_b, torch_a)

tensor([0, 1, 2, 1, 0])

In [22]:
#exponent / power
torch.pow(torch_a, torch_b)

tensor([      1,     128,    6561,  262144, 9765625])

In [23]:
#other method
torch_a**torch_b

tensor([      1,     128,    6561,  262144, 9765625])