<a href="https://colab.research.google.com/github/marif1991/pytorch-owais/blob/main/tensors_opera.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [6]:
my_torch = torch.arange (16)
my_torch

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [13]:
#reshape and view
my_torch = my_torch.reshape (4,4)
my_torch

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [14]:
# reshape, if we donot know the number of items using -1
my_torch2 = torch.arange(20)
my_torch2


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [19]:
my_torch2 = my_torch2.reshape (5,-1)
my_torch2

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [21]:
my_torch3 = torch.arange(30)
my_torch3


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [22]:
my_torch4 = my_torch3.view(3,10)
my_torch4

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [23]:
#what is the difference between the shape and view in pytorch
#https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch#:~:text=The%20semantics%20of%20reshape(),about%20the%20meaning%20of%20contiguous%20.


In [24]:
#with shape and view, we can uptdate the number
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [28]:
my_torch5[3] = 888
my_torch5

tensor([  0,   1,   2, 888,   4,   5,   6,   7,   8,   9])

In [29]:
my_torch6

tensor([[  0,   1,   2, 888,   4],
        [  5,   6,   7,   8,   9]])

In [30]:
#what is a sliece
my_torch7=torch.arange(20)
my_torch7

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [32]:
# Grab a specific item
my_torch7[10]

tensor(10)

In [34]:
#grab  a slice
my_torch8 = my_torch7.reshape(4,5)
my_torch8

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [35]:
my_torch8[:1]


tensor([[0, 1, 2, 3, 4]])

In [36]:
my_torch8[2:4]

tensor([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [37]:
my_torch8[0:1]

tensor([[0, 1, 2, 3, 4]])

In [38]:
my_torch8[:4:]

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [40]:
my_torch8[:, 1:]

tensor([[ 1,  2,  3,  4],
        [ 6,  7,  8,  9],
        [11, 12, 13, 14],
        [16, 17, 18, 19]])