<a href="https://colab.research.google.com/github/marif1991/pytorch-owais/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
my_list= [[1,2,3,4], [56789]]
my_list

[[1, 2, 3, 4], [56789]]

In [ ]:
np1=np.random.rand(3,4)
np1

array([[0.29963601, 0.05401129, 0.01641747, 0.6113432 ],
       [0.75652559, 0.68645817, 0.06634251, 0.7898353 ],
       [0.56602811, 0.38174402, 0.3400289 , 0.88513104]])

In [ ]:
np1.dtype

dtype('float64')

In [ ]:
np2=np.random.rand(3)
np2

array([0.93801658, 0.76327823, 0.30729898])

In [ ]:
tensor_2d=torch.randn(3,4)
tensor_2d
tensor_2d.dtype

torch.float32

In [ ]:
tensor_3d = torch.zeros (2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])